### ISSUE TITLE
[Suggestion] opaque event horizon

### ISSUE THREAD

**Issue by Nex4rius** [gcewing/SGCraft#19]
Could you make the event horizon opaque? In the series its only transparent when you look at it from behind but from the front its always opaque.

It would also "fix" those kind of glitches.
<img src="http://i.imgur.com/fqlbHFh.gif" width="700px">

**Comment by gcewing** [comment]
Nexarius wrote:

> Could you make the eventhorizon opaque?

There's a config option for that: 'transparency' in the 'stargate' section.

## 

Greg

**Comment by Nex4rius** [comment]
oh cool
I didn't see that.
