### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by ebauman** [gcewing/SGCraft#22]
Greetings,

I have been using SGCraft with my Tekkit Legends server for a little while now. I have setup gates across the countryside, and most have a dialing computer associated with them. These dialing computers are ComputerCraft Advanced Computers, connected to the gate interface with modems and networking cable. 

After I began using computers in this manner, I have been experiencing issues with server crashes. When examining the server logs, the following errors are present:

```
CCSGPeripheral.detach: from dan200.computercraft.shared.peripheral.modem.TileCable$RemotePeripheralWrapper@1f8a18ae
CCSGPeripheral.detach: from dan200.computercraft.shared.peripheral.modem.TileCable$RemotePeripheralWrapper@67e68df6
CCSGPeripheral.attach: to dan200.computercraft.shared.peripheral.modem.TileCable$RemotePeripheralWrapper@31fe7ecd
CCSGPeripheral.detach: from dan200.computercraft.shared.peripheral.modem.TileCable$RemotePeripheralWrapper@53d51ffc
CCSGPeripheral.detach: from dan200.computercraft.shared.peripheral.modem.TileCable$RemotePeripheralWrapper@31fe7ecd
```

Followed by:

```
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
    at java.util.HashMap$KeyIterator.next(HashMap.java:956)
    at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:269)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:648)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

I stopped using the computers altogether, and the errors disappeared, and the server remained stable.

It's worth noting here that I have played this same server (same forge, tekkit, CC versions) without SGCraft previously, and have not had issues with the advanced computers behaving in this manner.

Is it possible there is some issue with the SGCraft CC interface, and some kind of hazardous interaction with CC or the world?

Any assistance would be greatly appreciated.

**Comment by gcewing** [comment]
Eamon Bauman wrote:

> Is it possible there is some issue with the SGCraft CC interface, and 
> some kind of hazardous interaction with CC or the world?

It's possible, but in the absence of anything SG-related in the
traceback, I wouldn't know where to start looking. (The detach
messages don't necessarily represent errors, they just mean
something has been disconnected from the interface.)

Were you adding or removing any CC parts in the vicinity when
this happened?

## 

Greg

**Comment by ebauman** [comment]
I was not. To the best of my recollection (and I can go back and recreate the conditions this evening), I was dialing another stargate via the dialing computer when the errors occurred.

Which is to say, I use the advanced computer (using a slightly-modified example of the dialing software from the SGCraft website) to dial another gate, then exited the interface. Shortly after exiting (and while the gate was dialing), the game exited. 

I will recreate the conditions tonight and see if I can replicate the error. Are there any steps I should take, debug flags, etc. that would help with troubleshooting?

Thanks

**Comment by gcewing** [comment]
Eamon Bauman wrote:

> I will recreate the conditions tonight and see if I can replicate the 
> error. Are there any steps I should take, debug flags, etc. that would 
> help with troubleshooting?

Not really. But if you can find a way to reproduce it,
that will be a big help.

## 

Greg

**Comment by ebauman** [comment]
Greetings,

I have switched dialing programs and have been unable to replicate the issue.
I will be closing this ticket now unless the issue pops up again.
Thank you for your assistance thusfar!
