### ISSUE TITLE
[Suggestion] don't move the chevrons

### ISSUE THREAD

**Issue by Nex4rius** [gcewing/SGCraft#26]
I don't think it makes alot of sense to move the chevrons when you have a block in the stargate camouflage. I think you made it so it's possible to see all 9 chevrons even when the stargate base is completly covered but (in the series) they don't just "move up". It is one of those things that just looks weird for a hardcore stargate fan.
<img src="http://i.imgur.com/oUi1hBn.png">
<img src="http://i.imgur.com/Zv7hLYU.png">

**Comment by gcewing** [comment]
Nexarius wrote:
> I don't think it makes alot of sense to move the chevrons when you have 
> a block in the stargate camouflage.

What doesn't make sense to me is to have two chevrons embedded
in stone, particularly if they're going to move and/or light up.

Have you tried using half-slabs as camouflage? I've arranged it
so the chevrons only move slightly in that case,

-- 
Greg

**Comment by Nex4rius** [comment]
Using slabs as camouflage brings other problems because now its not completly in the ground and you now have a unnecessary step at the stargate.
<img src="http://i.imgur.com/vsPhEvl.jpg">

Could you maybe do a config inside the gui of the stargate(or in the config file) for moving the chevrons or not?

>What doesn't make sense to me is to have two chevrons embedded in stone, particularly if they're going to move and/or light up.

On the one side that makes sense but on the other side its just not how it worked / looked in the series.

**Comment by gcewing** [comment]
Yes, a config option is a good idea.

-- 
Greg
