### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 94

### ISSUE THREAD

**Issue by Ionaru** [gcewing/SGCraft#3]
Minecraft crashes during startup with the error 

```
java.lang.ArrayIndexOutOfBoundsException: 94
at gcewing.sg.BaseModClient.onTextureStitchEventPre(BaseModClient.java:657)
```

Full crash log:
http://pastebin.com/0PijQuA0

Related issue:
https://github.com/BluSunrize/ImmersiveEngineering/issues/987

Using SGCraft 1.11.0 for Minecraft 1.7.10

**Comment by StargateMC** [comment]
If this is fixed, please close @Ionaru :) - Just checked 1.11.1 notes.

**Comment by Ionaru** [comment]
Awesome, thanks!
