### ISSUE TITLE
[Suggestion] Config to disable Stargate temples

### ISSUE THREAD

**Issue by mura3277** [gcewing/SGCraft#37]
Would it be possible to add a config option for this? (1.7.10)

Makes it possible to balance the Stargate in a Modpack :D

Thanks.

**Comment by gcewing** [comment]
Muramasa- wrote:
> Would it be possible to add a config option for this? (1.7.10)

There already is, it's called augmentStructures.

**Comment by mura3277** [comment]
Oh, my mistake!
