### ISSUE TITLE
Update to 1.12.1

### ISSUE THREAD

**Issue by Dockter** [gcewing/SGCraft#49]
Hello,

Thought I would stop by and mention that AlmuraDev team has done an update to this mod for version 1.12.1 which your welcome to take and use.

Note: we removed CoFH cause working with that mod and sponge is just impossible...  This seems to be functional at the moment though we haven't testing everything completely as of yet.  We are also working on updating the transporter system to be compatible with Sponge.

https://github.com/AlmuraDev/SGCraft/commits/1.12.1

**Comment by Tsoccerguy3** [comment]
Make a pull request to merge your updates. Here's fast update to 1.12.2

There is just a small update to 1.12.2 . Out side of updating the mappings and MCP to 1.12.2 .
changes to build.gradle
to
`dependencies
    {        
        compile files('lib/industrialcraft-2-2.8.27-ex112-api.jar')
        compile files('lib/OpenComputers-MC1.12.1-1.7.0.20.jar')        
    }

minecraft {    
    version = "1.12.2-14.23.0.2515"
    runDir = "run"
    mappings = 'snapshot_20171022'    
    useDepAts = true`


need to change line 1057 in SGBaseTE.java

from

`// Break any leash connections to or from the given entity. That happens anyway
    // when the entity is teleported, but without this it drops an extra leash item.
    protected static void unleashEntity(Entity entity) {
        if (entity instanceof EntityLiving)
            ((EntityLiving)entity).clearLeashed(true, false);
        for (EntityLiving entity2 : entitiesWithinLeashRange(entity))
            if (entity2.getLeashed() && entity2.getLeashedToEntity() == entity)
                entity2.clearLeashed(true, false);
    }`

to

`// Break any leash connections to or from the given entity. That happens anyway
    // when the entity is teleported, but without this it drops an extra leash item.
    protected static void unleashEntity(Entity entity) {
        if (entity instanceof EntityLiving)
            ((EntityLiving)entity).clearLeashed(true, false);
        for (EntityLiving entity2 : entitiesWithinLeashRange(entity))
            if (entity2.getLeashed() && entity2.getLeashHolder() == entity)
                entity2.clearLeashed(true, false);
    }`

Last fix block texture names so you don't get the pink and black texture (missing texture) on your SG blocks

**Comment by Dockter** [comment]
I don't want to make a PR because I removed one of its features in my branch.

**Comment by Tsoccerguy3** [comment]
Thats Kool , Thanks for sharing , It's great that you updated to 1.12.1. Maybe if you have time to patch to 1.12.2 on a new branch. Have a great day .

**Comment by Dockter** [comment]
I have completed this in our continuation of this project branch.  Builds can be found here:  https://ore.spongepowered.org/Dockter/SGCraft
