### ISSUE TITLE
Power unit not available

### ISSUE THREAD

**Issue by Liiw** [gcewing/SGCraft#5]
Hello. I have installed SGCraft on Minecraft 1.8.9 along with other mods, including JEI. While testing the mods for compatibility, I noticed, via JEI, that the Stargate RF power supply is not available to craft or to acquire by cheating. It was available in the 1.7.10 version. Could this be a bug of some sort? I understand there might be a need for more detailed information. If so, please let me know, what to provide.

Oh, the version of the mod is: SGCraft-1.11.2-mc1.8.9.jar

**Comment by gcewing** [comment]
Liiw wrote:

> I noticed, via JEI, that the Stargate RF power supply is not available

Power units are not implemented in the 1.8 version yet, sorry.

## 

Greg

**Comment by Liiw** [comment]
Ah, I see. Well that settles it then. Thank you for your reply, I will close the matter for now. I hope you have time to implement it. 

In any case, this is an excellent mod!
